#
# this module look for SDL2_Mixer (http://www.libsdl.org) support
# it will define the following values
#
# SDL2MIXER_INCLUDE_DIR  = where SDL_mixer.h can be found
# SDL2MIXER_LIBRARY      = the library to link against SDL2_mixer
# SDL2MIXER_FOUND        = set to 1 if SDL2_mixer is found
#

IF(SDL2_Mixer_INCLUDE_DIRS)

  FIND_PATH(SDL2MIXER_INCLUDE_DIR SDL2/SDL_mixer.h ${SDL2_Mixer_INCLUDE_DIRS})
  FIND_LIBRARY(SDL2MIXER_LIBRARY SDL2_mixer ${SDL2_Mixer_LIBRARY_DIRS})

ELSE(SDL2_Mixer_INCLUDE_DIRS)

  SET(TRIAL_LIBRARY_PATHS
    $ENV{SDL2_MIXER_HOME}/lib
    /usr/lib
    /usr/local/lib
    /sw/lib
  ) 
  SET(TRIAL_INCLUDE_PATHS
    $ENV{SDL2_MIXER_HOME}/include/SDL2
    /usr/include/SDL2
    /usr/local/include/SDL2
    /sw/include/SDL2
  ) 

  FIND_LIBRARY(SDL2MIXER_LIBRARY SDL2_mixer ${TRIAL_LIBRARY_PATHS})
  FIND_PATH(SDL2MIXER_INCLUDE_DIR SDL_mixer.h ${TRIAL_INCLUDE_PATHS})

ENDIF(SDL2_Mixer_INCLUDE_DIRS)

IF(SDL2MIXER_INCLUDE_DIR AND SDL2MIXER_LIBRARY)
  SET(SDL2MIXER_FOUND 1 CACHE BOOL "Found SDL2_Mixer library")
ELSE(SDL2MIXER_INCLUDE_DIR AND SDL2MIXER_LIBRARY)
  SET(SDL2MIXER_FOUND 0 CACHE BOOL "Not found SDL2_Mixer library")
ENDIF(SDL2MIXER_INCLUDE_DIR AND SDL2MIXER_LIBRARY)

MARK_AS_ADVANCED(
  SDL2MIXER_INCLUDE_DIR
  SDL2MIXER_LIBRARY
  SDL2MIXER_FOUND
)
